name: radio_palavra_antiga
description: Aplicação Android oficial da Rádio Palavra Antiga.
publish_to: "none"
version: 1.0.12+13

environment:
  sdk: ^3.12.0

dependencies:
  audio_service: ^0.18.19
  audio_session: ^0.2.4
  connectivity_plus: ^7.3.1
  flutter:
    sdk: flutter
  http: ^1.6.0
  in_app_purchase: ^3.3.0
  just_audio: ^0.10.6
  path_provider: ^2.1.6
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  vehicle_connection_monitor:
    path: packages/vehicle_connection_monitor
  webview_flutter: ^4.14.1
  webview_flutter_android: ^4.13.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/data/official_playlists.json
    - web_integration/rpa_bridge.js
